project/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'project'

urlpatterns = [
    path('', views.index, name='index'),
    path('(?P<album_id>[0-9]+)/', views.details, name='details'),
    path('add_album', views.add_album, name='add_album'),
    path('(?P<album_id>[0-9]+)/add_song', views.add_song, name='add_song'),
    path('(?P<album_id>[0-9)+)/delete-album', views.delete_album, name='delete-album'),
    path('signup', views.signup, name='signup'),
   # path('login', auth_views.LoginView.as_view(), name='login'),
    #path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout')
]

python/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
GENRE = (
    ('Unknown', 'unknown'),
    ('Rap', 'rap'),
    ('Redeem', 'Redeem'),
    ('Rnb', 'rnb'),
    ('Bongo', 'Bongo'),
    ('Local', 'local'),
    ('Trap', 'trap')
)


class Album(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    artist = models.CharField(max_length=40)
    year = models.CharField(max_length=4)
    cover = models.ImageField()
    genre = models.CharField(choices=GENRE, max_length=30, default='unknown')

    def __str__(self):
        return self.name


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    audio = models.FileField()

    def __str__(self):
        return self.name

project/forms.py
from django import forms
from .models import Album, Song
from django.contrib.auth.models import User


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['name', 'artist', 'cover', 'genre', 'year']


class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['name', 'audio']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

project/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Album
from .forms import AlbumForm, SongForm, UserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required(login_url='project:login')
def index(request):
    albums = Album.objects.filter(user=request.user)
    context = {
        'albums': albums
    }
    return render(request, 'project/index.html', context)


def details(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    context = {
        'album': album
    }

    return render(request, 'project/details.html', context)


@login_required(login_url='project:login')
def add_album(request):
    form = AlbumForm(request.POST or None, request.FILES or None)
    context = {
        'form': form
    }
    if form.is_valid():
        album = form.save(commit=False)
        album.cover = request.FILES['cover']
        album.user = request.user
        album.save()
        return render(request, 'project/details.html', {'album': album})

    return render(request, 'project/add_album.html', context)


def add_song(request, album_id):
    form = SongForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=album_id)
    if form.is_valid():
        song = form.save(commit=False)
        song.audio = request.FILES['audio']
        album.user = request.user
        song.album = album
        song.save()
        return render(request, 'project/details.html', {'album': album})

    return render(request, 'project/add_song.html', {'form': form})


def delete_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    album.delete()
    return redirect('project:index')


def signup(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = form.save(commit=False)
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('project:index')

    return render(request, 'project/signup.html', {'form': form})


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('project:index')

    return render(request, 'registration/login.html')


def logout_user(request):
    logout(request)
    return redirect('project:login')

project/templates/project/add_album.html
{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Marck Script' rel='stylesheet'>

<div class="container">
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <div class="panel panel-default" style="margin: 2px; font-family: 'Marck Script'; ">
                <div class="panel-body">
                    <h4 class="text-primary">Add Album</h4>
                    <hr>
                     <form method="post" enctype="multipart/form-data">
                        {% csrf_token%}
                        {{ form|crispy }}
                        <div class="form-group" style="margin: 3px">
                            <button type="submit" class="btn btn-info">Submit</button>
                         </div>
                     </form>
                </div>
            </div>

        </div>
        <div class="col-sm-4"></div>

    </div>
</div>

project/templates/project/add_song.html
{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Marck Script' rel='stylesheet'>

<div class="container">
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <div class="panel panel-default" style="margin: 2px; font-family: 'Marck Script';">
                <div class="panel-body">
                    <h4 class="text-primary">Add Song</h4>
                    <hr>
                     <form method="post" enctype="multipart/form-data">
                        {% csrf_token%}
                        {{ form|crispy }}
                         <div class="form-group" style="margin: 3px">
                            <button class="btn btn-primary" type="submit">Submit</button>
                         </div>
                     </form>
                </div>
            </div>

        </div>
        <div class="col-sm-4"></div>

    </div>
</div>

project/templates/project/details.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Marck Script' rel='stylesheet'>

<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <div class="panel panel-info">
                <div class="panel-body">
                    <img src="{{ album.cover.url }}" class="img img-thumbnail img-responsive" alt="" style="font-family: 'Marck Script'; height: 250px; width: 250px">
                    <div class="caption">
                        <h5>{{ album.name }}</h5>
                        <h6>{{ album.genre }}</h6>

                    </div>

                </div>
            </div>

        </div>
        <!-- End Album Information -->
        <!-- Song Information -->

        <div class="col-sm-9">
            <ul class="nav nav-pills">
                <li class="active"><a href="">Songs</a> </li>
                <li><a href="{% url 'project:add_song' album.id%}">Add Song</a></li>
            </ul>
            <div class="panel panel-default" style="margin: 2px;">
                <div class="pane panel-body">
                    <h4 class="text-primary">All Songs</h4>
                    <table class="table">
                        <tr>
                            <thead>
                            <th>#</th>
                            <th>Song name</th>
                            <th>Audio</th>
                            <th>Favourite</th>
                            <th>Action</th>
                            </thead>
                        </tr>
                        <tbody>
                        {% if album.song_set %}
                            {% for s in album.song_set.all %}
                                <tr>
                                <td>{{ album.id }}</td>
                                <td>{{ s.name }}</td>
                                <td><a href="{{ s.audio.url }}" class="btn btn-info btn-sm" target="_blank">
                                    <i class="fas fa-play-circle"></i>
                                </a>
                                </td>
                                    <td>
                                        <a href="" class="btn btn-primary btn-sm">
                                            <i class="fas fa-heart"></i>
                                        </a>
                                    </td>
                                <td>
                                    <a href="" class="btn btn-success">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a href="" class="btn btn-danger">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

project/templates/project/index.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Akronim' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet'>

{% load static %}
<link rel="stylesheet" href="{% static 'project/css/style.css' %}" type="text/css">



<div class="container">
    <div class="row">
        {% for album in albums %}
            <div class="col-sm-3">
            <div class="panel panel-default" style="margin: 2px">
                <a href="{% url 'project:details' album.id %}">
                    <img src="{{ album.cover.url }}" class="img img-thumbnail img-responsive" alt="" style="height: 250px; width: 250px">
                </a>
                <div class="caption" style="margin: 3px; font-family: 'Satisfy' ">
                    <h5>{{ album.name }}</h5>
                    <h6>{{ album.artist }}</h6>
                    <a href="" class="btn btn-primary btn-sm">
                        <i class="fas fa-edit"></i>
                    </a>
                    <a href="" class="btn btn-info btn-sm">
                        <i class="fas fa-heart"></i>
                    </a>
                    <a href="{% url 'project:delete-album' album.id %}" class="btn btn-danger btn-sm" style="float: right"
                    onclick='return confirm("Are you sure you want to delete")'>
                        <i class="fas fa-trash"></i>
                    </a>
                </div>
            </div>
            </div>


        {% endfor %}



    </div>
</div>

project/templates/project/signup.html
{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<div class="container">
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <div class="panel panel-default" style="margin: 2px; font-family: 'Akronim';">
                <div class="panel-body">
                    <h4 class="text-primary">SignUp</h4>
                    <hr>
                     <form method="post" enctype="multipart/form-data">
                        {% csrf_token%}
                        {{ form|crispy }}
                        <div class="form-group" style="margin: 3px">
                            <button type="submit" class="btn btn-info">Submit</button>
                         </div>
                     </form>
                </div>
            </div>

        </div>
        <div class="col-sm-4"></div>

    </div>
</div>